labsyspharm/ashlar

ashlar/reg.py
This is a problem with pyjnius and the most recent versions of cython which corrupts Python strings passed to Java methods under Python 3 (kivy/pyjnius#300). Explicitly constructing a Java string to pass to Java does work, so this is the solution used here.
=> Work around kivy/pyjnius#300

Dockerfile
Previously it installed from pypi, but this meant one could only build
the latest deployed version and not github tags or branches.
=> Change Dockerfile to install ashlar from local files

ashlar/reg.py, ashlar/scripts/ashlar.py
The original code set the maximum corrective shift distance as a fraction of
the tile image size. Stage accuracy is more accurately modeled in absolute
microns. The current default of 15 microns seems reasonable for the microscopes
we have tested with.
=> Change max-shift to microns and expose on command line

ashlar/reg.py
The fixes include
- Handle illumination images more than 4 channels
- When the `--output-channels` arg is set, the correct channel in the illumination profiles is used
(Sorry for the messy commits, please squash them when merging)
=> Fix load illumination profiles

Dockerfile, ashlar/filepattern.py, ashlar/fileseries.py, ashlar/reg.py, ashlar/scripts/ashlar.py, ashlar/thumbnail.py, ashlar/zen.py, setup.py
* Remove compatibility imports and deprecation warning
* Update dependency versions (including some py3-only releases)
* Update Dockerfile to run with Python 3 instead of 2
=> Drop Python 2 support

ashlar/utils.py
When computing element-wise dot product of bright-field images with fluorescent images, the same features (e.g. border of a nucleus) will be in different signs after whitening (Laplace filter). Pixel correlation is represented by taking the absolute value of the result in this context.
=> Take absolute value when computing pixel correlation

ashlar/reg.py, ashlar/scripts/ashlar.py, setup.py
The command line "ashlar" tool now prints errors and relevant warnings in a
consistent format, with optional color.
=> Improve warning and error output

ashlar/scripts/ashlar.py, setup.py
Switch from blessings, which does not support Windows (even though its
documentation claimed otherwise), to blessed, a fork which does.
=> Fix support for terminal colors on Windows

ashlar/scripts/ashlar.py
I worked from some example code at https://pymotw.com/2/warnings/ but
didn't test it with regular warnings (the ones we don't specially
format ourselves). I should have double-checked the actual signature
of warnings.formatwarning myself.
=> Fix warning formatter function signature

ashlar/filepattern.py, ashlar/fileseries.py, ashlar/zen.py
Previously, the readers using skimage.io.imread would return a 3D image array
when passed multi-plane image files, even if they only expected 2D images. These
3D images caused various problems when they "escaped" into the image handling
parts of the code. This change updates these readers to be more defensive and
explicitly read only the first image plane.
=> Make non-bioformats readers tolerant of multi-plane images

ashlar/scripts/preview_slide.py, ashlar/utils.py
* Stop using subpixel precision when compositing, for performance.
* Add -l argument to log-scale pixel intensities. This is useful when
images contain a few bright spots which throws off matplotlib's automatic
dynamic range adjustment. For the rough previews this tool is designed
for, this option should possibly be on by default.
=> Improve preview_slide performance and add log scaling

ashlar/reg.py
With one tile, the EdgeAligner linear model ended up with a transform
matrix of all zeros, which led the LayerAligner to make incorrect
predictions about the expected location of the tiles in the later cycles
and thus reject them too often. In this change we detect the degenerate
transform and reset it to the identity matrix.
=> Fix aligning multiple single-tile cycles

ashlar/utils.py
The tile blending uses an alpha mask computed from the distance transform, but
was not taking into account the possibility of zero-valued pixels in the actual
images. A morphological hole-removal step was added to fix this problem.
Ultimately this should be addressed by using the known tile bounds to
initialize the mask for the distance transform, but that will require some
refactoring.
=> Fix defect in mosaic tile blending logic

ashlar/reg.py
The permutation test uses random to generate error threshold for the cross-correlation. Slightly changes in the threshold may affect the minimal spanning tree and the stitching results. Specify a seed (0) when constructing the random state allows reproducible stitching.
=> Fix random state by default for reproducible stitching result

ashlar/reg.py
* Disable auto-tile-stitching in the BioFormats CZI reader
* Disable reading "attachments" like the label image
=> Fix various issues reading .CZI files

ashlar/reg.py, ashlar/scripts/preview_slide.py
This allows useful presentation of the mosaic image in the figures generated by
plot_edge_quality etc. even without the old modest_image package.  The
aligner.reader.thumbnail image is usually a perfectly serviceable image to use
here.
=> Allow downsampled images to be used in the plot helpers

ashlar/filepattern.py
The filepattern reader now correctly uses the set of channel strings
parsed from the filenames rather than their 0-based indexes. This fixes
the reader when channels are numbers that don't start at 0 or arbitrary
strings.
=> Fix parsing of channel in filenames

ashlar/reg.py
Bools are now auto-converted to Integers instead of Booleans, so we have to
perform the conversion explicitly now. Tracked upstream in kivy/pyjnius#602 .
=> Work around pyjnius mishandling of bool args

ashlar/reg.py
If pixel X and Y dimensions are different but within a 1e-4 relative tolerance,
issue a warning and use the X dimension when stitching and writing output file
metadata. Dimensions outside of that tolerance will still raise an exception.
Fixes #122
=> Tolerate very slightly non-square pixels

.github/workflows/ci.yml
The automated test builds a temporary container image and applies it to `exemplar-001` for `push` and `pull_request` events on all branches.
Specific features:
* Will not be triggered by changes to the `docs/` folder
* Can be triggered manually in the GitHub Actions web interface
* Will cache `exemplar-001`, removing the need to download it from AWS for every run
* Will make the output `exemplar-001.ome.tif` available as a downloadable artifact in the GHA web interface. This allows for additional manual inspection using one's favorite image viewer.
=> Automated test for continuous integration

ashlar/reg.py, ashlar/scripts/ashlar.py
* Avoid erroring when --version is given (fixes #125)
* Correct nargs from * to + for several arguments
* Text edits to simplify and clarify argument help strings
* Add or correct documented default values
* Hide help for deprecated -f and --pyramid arguments
* Streamline logic and improve warnings and errors around handling the
deprecation of the -f argument.
* Fix logic for nonexistent output directory warning
* Show TiffListWriter overwrite warning on first instance, not second
=> Improve argument parsing and help text

ashlar/reg.py
Fixes a crash when the output image is smaller than the tile size.
=> Set minimum number of pyramid levels to 1

ashlar/filepattern.py, ashlar/fileseries.py
The `fileseries` and `filepattern` readers can now accept any image format readable by `skimage.io.imread`, not just TIFF. Notably, this includes JPEG and PNG which have been requested by several users. RGB images are treated as having 3 channels. Fixes #121.
=> Support common RGB image formats in fileseries/filepattern

ashlar/reg.py, ashlar/scripts/ashlar.py
* Store image series indexes as lists of Python ints instead of numpy arrays
as pyjnius doesn't seem to detect and cast numpy.int64 like it used to.
* Improve the output filename generation to avoid creating the last level
of directories per well if not needed (i.e. with OME-TIFF output).
=> Fix regressions in plates (HTS) mode

ashlar/reg.py
We should also enable the predictor but there is a bug in tifffile (#185)
=> Use zlib compression in ome-tiff output

ashlar/reg.py, ashlar/thumbnail.py
Thumbnails now have a minimum size of 1000 pixels on the longest side and cross-blending is used to combine the tiles in the thumbnail instead of max-intensity projection. This improves coarse alignment for very small images. It also yields a more reliable estimate of rotation between cycles (correction of which is coming soon).
=> Improve coarse-alignment thumbnail quality

README.md, ashlar/reg.py, ashlar/scripts/ashlar.py
These arguments allow tuning of the edge alignment error quantification. --stitch-alpha is a more general-purpose knob (sets the significance level) whereas --maximum-error should only be used when very specific control over the threshold is needed. --maximum-error is undocumented by design. The forthcoming QC report output will help inform the choice of this value at which point we will document it.
=> Add --stitch-alpha and --maximum-error args

ashlar/reg.py, ashlar/scripts/ashlar.py, ashlar/transform.py, ashlar/utils.py
This adds a `--barrel-correction` argument that takes a single floating point value which is used in a simple one-parameter image warping model to correct for barrel/pincushion distortion. The parameter is deliberately undocumented as the process for choosing its value is not yet well defined.
=> Add barrel/pincushion correction support

ashlar/reg.py
Now we look at the determinant of the matrix of coefficients, not just whether all the individual values are zero. Also the intercept is now zeroed out which fixes the single tile placed far from the rest (even though this was a sign of complete EdgeAligner failure). A warning is emitted in the failure case to alert the user of the problem.
=> Correct handling of linear model fitting failure

ashlar/filepattern.py, ashlar/fileseries.py
This allows literal parentheses in filenames to be matched.
=> Escape parentheses in fileseries/filepattern pattern

ashlar/reg.py
If an input image has a thumbnail or other subresolution image, this change will allow us to read it without getting tripped up by the subresolutions.
=> Tell Bioformats not to "flatten" pyramids

README.md, docs/instructions/installation.md
Tifffile's zarr integration doesn't support zarr 3, and we are using a tifffile feature that's been discontinued in the latest version. This changes restricts those packages' versions to compatible ones.
=> Restrict zarr and tifffile versions
